"""initial governance schema

Revision ID: 3effed83f675
Revises: 
Create Date: 2026-08-20 07:06:41.439453

"""
from alembic import op
import sqlalchemy as sa
import app.models


revision = '3effed83f675'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'PAUSED', 'BLOCKED', name='agentstate'), nullable=False),
    sa.Column('active_profile_id', app.models.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_profiles',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('agent_id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('agent_id', app.models.GUID(), nullable=False),
    sa.Column('run_id', app.models.GUID(), nullable=False),
    sa.Column('tool_used', sa.String(), nullable=True),
    sa.Column('data_source_used', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', app.models.GUID(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['agent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', app.models.GUID(), nullable=False),
    sa.Column('data_source_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['agent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', app.models.GUID(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['agent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('agent_id', app.models.GUID(), nullable=False),
    sa.Column('run_id', app.models.GUID(), nullable=False),
    sa.Column('event_id', app.models.GUID(), nullable=True),
    sa.Column('finding_type', sa.Enum('UNAUTHORIZED_TOOL', 'UNAUTHORIZED_DATA', 'UNAUTHORIZED_ACTION', 'GUARDRAIL_WARNING', 'GUARDRAIL_CRITICAL', 'GUARDRAIL_LIMIT', name='findingtype'), nullable=False),
    sa.Column('expected', sa.String(), nullable=False),
    sa.Column('actual', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity'), nullable=False),
    sa.Column('response_action', sa.Enum('NOTIFY', 'REQUIRE_APPROVAL', 'BLOCK', name='responseaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardrails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', app.models.GUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=False),
    sa.Column('warning_pct', sa.Integer(), nullable=True),
    sa.Column('critical_pct', sa.Integer(), nullable=True),
    sa.Column('last_warning_level', sa.Enum('NONE', 'WARNING', 'CRITICAL', 'LIMIT', name='warninglevel'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['agent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('agent_id', app.models.GUID(), nullable=False),
    sa.Column('finding_id', app.models.GUID(), nullable=True),
    sa.Column('event_type', sa.Enum('FINDING_CREATED', 'STATE_CHANGED', 'APPROVAL_REQUESTED', 'APPROVED', 'REJECTED', name='auditeventtype'), nullable=False),
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_table('guardrails')
    op.drop_table('findings')
    op.drop_table('allowed_tools')
    op.drop_table('allowed_data_sources')
    op.drop_table('allowed_actions')
    op.drop_table('events')
    op.drop_table('agent_profiles')
    op.drop_table('agents')
    # ### end Alembic commands ###
